# Generated by Django 4.0 on 2023-08-31 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gestionmenu.models_perso


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauxColleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(blank=True, default='', max_length=20)),
                ('horaire', models.CharField(blank=True, default='', max_length=20)),
                ('salle', models.CharField(blank=True, default='', max_length=20)),
                ('matière', models.CharField(blank=True, default='', max_length=20)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('parent', models.IntegerField(blank=True)),
                ('fonction', models.CharField(blank=True, default='', max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('gestionnaires', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groupes', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'ordering': ['parent', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Renseignements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('année', models.IntegerField(blank=True, null=True)),
                ('seullogement', models.BooleanField(blank=True, null=True)),
                ('motivationprepa', models.TextField(blank=True, null=True)),
                ('lyceeorigine', models.CharField(blank=True, max_length=50, null=True)),
                ('villelyceeorigine', models.CharField(blank=True, max_length=50, null=True)),
                ('professionparents', models.TextField(blank=True, null=True)),
                ('freressoeurs', models.TextField(blank=True, null=True)),
                ('calculatrice', models.CharField(blank=True, max_length=50, null=True)),
                ('tempstrajet', models.IntegerField(blank=True, null=True)),
                ('accessordinateur', models.BooleanField(blank=True, null=True)),
                ('connexioninternet', models.BooleanField(blank=True, null=True)),
                ('coursconfinementmath', models.CharField(blank=True, choices=[['1', '1 :quasi inexistant'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5 : sans changement notable']], max_length=1, null=True)),
                ('coursconfinementphysique', models.CharField(blank=True, choices=[['1', '1 :quasi inexistant'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5 : sans changement notable']], max_length=1, null=True)),
                ('confinementcommentaire', models.TextField(blank=True, null=True)),
                ('notesbac', models.TextField(blank=True, null=True)),
                ('prenomofficiel', models.CharField(blank=True, max_length=50, null=True)),
                ('nomofficiel', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance_officiel', models.DateField(blank=True, null=True)),
                ('rne_lycee', models.CharField(blank=True, max_length=50, null=True)),
                ('lycee_officiel', models.CharField(blank=True, max_length=50, null=True)),
                ('ville_officiel', models.CharField(blank=True, max_length=50, null=True)),
                ('departement_officiel', models.CharField(blank=True, max_length=50, null=True)),
                ('note_initiale', models.FloatField(blank=True, null=True)),
                ('note_finale', models.FloatField(blank=True, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('modif_auto', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semaines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgColle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('description', models.CharField(default='', max_length=5000)),
                ('programme', models.FileField(blank=True, null=True, upload_to=gestionmenu.models_perso.ProgColle.uploadpathprog)),
                ('nomprogramme', models.CharField(blank=True, max_length=100, null=True)),
                ('exercices', models.FileField(blank=True, null=True, upload_to=gestionmenu.models_perso.ProgColle.uploadpathexos)),
                ('nomexercices', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.menu')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='NotesColles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('creneau', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionmenu.creneauxcolleurs')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='auth.user')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.semaines')),
            ],
        ),
        migrations.CreateModel(
            name='InfoColleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matière', models.CharField(blank=True, default='', max_length=20)),
                ('colleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeColles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('eleves', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_colles_individuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(blank=True, max_length=100, null=True)),
                ('titre', models.CharField(blank=True, max_length=100, null=True)),
                ('max_par_eleve', models.IntegerField()),
                ('max_garanti', models.IntegerField()),
                ('modif_par_eleves', models.BooleanField()),
                ('responsables', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierFiches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=gestionmenu.models_perso.FichierFiches.uploadpath)),
                ('nomfichier', models.CharField(blank=True, max_length=100, null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.renseignements')),
            ],
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=gestionmenu.models_perso.Fichier.uploadpath)),
                ('nomfichier', models.CharField(blank=True, max_length=100, null=True)),
                ('ordre', models.IntegerField(blank=True, null=True)),
                ('date_parution', models.DateField(blank=True, null=True)),
                ('type_fichier', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.menu')),
            ],
            options={
                'ordering': ['-ordre'],
            },
        ),
        migrations.CreateModel(
            name='Colloscope_individuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionnel', models.BooleanField(blank=True, default=False, null=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.creneauxcolleurs')),
                ('eleve', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.semaines')),
            ],
        ),
        migrations.CreateModel(
            name='Colloscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.creneauxcolleurs')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.groupecolles')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmenu.semaines')),
            ],
        ),
    ]
