# Generated by Django 4.0 on 2023-08-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(blank=True, default=None, null=True)),
                ('csrf_token', models.TextField(blank=True, default=None, null=True)),
                ('en_attente_confirmation', models.BooleanField(blank=True, default=True)),
                ('reinitialisation_password', models.BooleanField(blank=True, default=False)),
                ('autorise_modif', models.BooleanField(blank=True, default=True)),
                ('doit_changer_mdp', models.BooleanField(blank=True, default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
